# Generated by Django 4.2.1 on 2023-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=240)),
                ("apellido", models.CharField(max_length=240)),
                ("telefono", models.CharField(max_length=240)),
                ("email", models.EmailField(max_length=240)),
                ("empresa", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=240)),
                ("apellido", models.CharField(max_length=240)),
                ("telefono", models.CharField(max_length=240)),
                ("email", models.EmailField(max_length=240)),
                ("sector", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=240)),
                ("modelo", models.CharField(max_length=240)),
                ("proveedor", models.CharField(max_length=240)),
            ],
        ),
    ]
