# Generated by Django 4.2 on 2023-05-12 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Producto",
            new_name="Productos",
        ),
    ]
