# Generated by Django 4.2.1 on 2023-05-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0002_rename_producto_productos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Productos",
            new_name="Producto",
        ),
        migrations.AddField(
            model_name="cliente",
            name="dni",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personal",
            name="dni",
            field=models.IntegerField(default=0),
        ),
    ]
